### ISSUE TITLE
update all API calls to HTTPS 

### ISSUE THREAD

**Issue by pz64** [marcoacierno/pastebin-java-api#5]
Pastebin Announced that they will block all HTTP api calls after August 1. So please change all calls to HTTPS.

**Comment by marcoacierno** [comment]
Done in 6d0d3b48efc46018508128009827f77500fab2ed, just need to build a new jar + restore the maven repo because right now it doesn't work

**Comment by pz64** [comment]
Sorry, I dont know how to build jar Lib..will you please build and give a link to download

**Comment by pz64** [comment]
https://play.google.com/store/apps/details?id=pzy64.pastebin

This is what I made using your Lib.

**Comment by pz64** [comment]
please give the jar file before August 1

**Comment by marcoacierno** [comment]
can you check if it works for you?

[Pastebin-0.2.0.zip](https://github.com/marcoacierno/pastebin-java-api/files/1020215/Pastebin-0.2.0.zip)

**Comment by pz64** [comment]
It's working fine, THANKS!!
